remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: Intesive Kotlin class
description: Wanna get more about Kotlin language, this is the right page for a intensive study guide for you.
