title: Kotlin Intensive 
logo: /assets/img/logo.png
description: Wanna get more about Kotlin language, this is the right page, checkout the contents.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
